// frontend/pages/login.vue
<script setup lang="ts">
definePageMeta({ layout: false })

const auth = useAuthStore()
const route = useRoute()
const router = useRouter()

const role = ref<'VERKAUF' | 'ADMIN'>('VERKAUF')
const name = ref('')
const klasse = ref('')
const password = ref('')
const error = ref<string | null>(null)
const busy = ref(false)

async function submit() {
  if (busy.value) return
  if (!name.value.trim()) return
  if (!password.value) {
    error.value = 'Bitte Passwort eingeben.'
    return
  }
  if (role.value === 'VERKAUF' && !klasse.value.trim()) {
    error.value = 'Bitte Klasse eingeben.'
    return
  }

  busy.value = true
  error.value = null
  try {
    await auth.login({
      role: role.value,
      name: name.value.trim(),
      klasse: role.value === 'VERKAUF' ? klasse.value.trim() : undefined,
      password: password.value,
    })
    const next = typeof route.query.next === 'string' ? route.query.next : null
    await router.replace(next && next.startsWith('/') ? next : (auth.user?.role === 'ADMIN' ? '/admin' : '/'))
  } catch (e: any) {
    if (e?.response?.status === 401) error.value = 'Anmeldung fehlgeschlagen. Falsche Zugangsdaten.'
    else if (e?.response?.status === 400) error.value = e?.data?.message ?? 'Ungültige Eingabe.'
    else error.value = 'Server nicht erreichbar.'
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <div class="login-wrap">
    <div class="login-card">
      <div class="brand">
        <div class="brand-mark">K</div>
        <div class="brand-text">
          <div class="t1">Schulkasse</div>
          <div class="t2">Kuchenverkauf · Anmeldung</div>
        </div>
      </div>

      <div style="margin-bottom:12px">
        <label class="label">Name</label>
        <input
          class="input"
          autofocus
          autocomplete="name"
          v-model="name"
          @keydown.enter="submit"
          placeholder="z. B. Lena Müller" />
      </div>

      <div v-if="role === 'VERKAUF'" style="margin-bottom:12px">
        <label class="label">Klasse</label>
        <input
          class="input"
          v-model="klasse"
          @keydown.enter="submit"
          placeholder="z. B. BG12e" />
      </div>

      <div style="margin-bottom:14px">
        <label class="label">Passwort</label>
        <input
          class="input"
          type="password"
          autocomplete="current-password"
          v-model="password"
          @keydown.enter="submit"
          :placeholder="role === 'VERKAUF' ? 'Klassenpasswort' : 'Admin-Passwort'" />
      </div>

      <div>
        <label class="label">Anmelden als</label>
        <div class="role-pick">
          <label :class="role === 'VERKAUF' ? 'sel' : ''">
            <input type="radio" name="role" value="VERKAUF" v-model="role" />
            <span>👋 Verkäufer:in</span>
          </label>
          <label :class="role === 'ADMIN' ? 'sel' : ''">
            <input type="radio" name="role" value="ADMIN" v-model="role" />
            <span>🔑 Admin</span>
          </label>
        </div>
      </div>

      <button class="btn big" style="margin-top:18px" @click="submit" :disabled="busy">
        {{ busy ? 'Anmelden…' : 'Schicht beginnen →' }}
      </button>

      <div v-if="error" style="margin-top:14px;color:var(--bad);font-size:13px">{{ error }}</div>
    </div>
  </div>
</template>

// design/project/js/Login.jsx
// Login.jsx
const { useState } = React;

function Login({onLogin, recent}){
  const [name,setName] = useState('');
  const [klasse,setKlasse] = useState('');
  const [role,setRole] = useState('verkauf'); // verkauf | admin

  const submit = () => {
    if(!name.trim()) return;
    onLogin({name:name.trim(), klasse:klasse.trim(), role, startedAt:Date.now()});
  };

  return (
    <div className="login-wrap">
      <div className="login-card">
        <div className="brand">
          <div className="brand-mark">K</div>
          <div className="brand-text">
            <div className="t1">Schulkasse</div>
            <div className="t2">Kuchenverkauf · Anmeldung</div>
          </div>
        </div>

        <div style={{marginBottom:12}}>
          <label className="label">Name</label>
          <input className="input" autoFocus value={name}
                 onChange={e=>setName(e.target.value)}
                 onKeyDown={e=>e.key==='Enter'&&submit()}
                 placeholder="z. B. Lena Müller" />
        </div>

        <div style={{marginBottom:14}}>
          <label className="label">Klasse / Rolle (optional)</label>
          <input className="input" value={klasse}
                 onChange={e=>setKlasse(e.target.value)}
                 onKeyDown={e=>e.key==='Enter'&&submit()}
                 placeholder="z. B. 9b · Elternbeirat" />
        </div>

        <div>
          <label className="label">Anmelden als</label>
          <div className="role-pick">
            <label className={role==='verkauf'?'sel':''}>
              <input type="radio" name="role" value="verkauf"
                     checked={role==='verkauf'} onChange={()=>setRole('verkauf')} />
              <span>👋 Verkäufer:in</span>
            </label>
            <label className={role==='admin'?'sel':''}>
              <input type="radio" name="role" value="admin"
                     checked={role==='admin'} onChange={()=>setRole('admin')} />
              <span>🔑 Admin</span>
            </label>
          </div>
        </div>

        <button className="btn big" style={{marginTop:18}} onClick={submit}>
          Schicht beginnen →
        </button>

        {recent && recent.length>0 && (
          <>
            <div style={{marginTop:18,fontSize:11.5,color:'var(--ink-3)',fontWeight:600,textTransform:'uppercase',letterSpacing:'.06em'}}>
              Zuletzt angemeldet
            </div>
            <div className="recent-users">
              {recent.map((r,i)=>(
                <button key={i} className="chip"
                        onClick={()=>onLogin({name:r.name, klasse:r.klasse, role:r.role||'verkauf', startedAt:Date.now()})}>
                  {r.name}{r.klasse?' · '+r.klasse:''}
                </button>
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  );
}

window.Login = Login;
