// frontend/components/PayModal.vue
<script setup lang="ts">
import { formatEUR } from '~/utils/format'
import { NOTES, COINS } from '~/utils/denoms'
import type { CartItem, SaleDto } from '~/types/api'

const props = defineProps<{
  open: boolean
  items: CartItem[]
}>()

const emit = defineEmits<{
  close: []
  paid: [sale: SaleDto]
}>()

type Stage = 'choose' | 'cash' | 'card' | 'done'
const stage = ref<Stage>('choose')
const givenCents = ref(0)
const finished = ref<SaleDto | null>(null)
const cardError = ref<string | null>(null)
const cardWaiting = ref(false)

const totalCents = computed(() => props.items.reduce((t, x) => t + x.priceCents * x.qty, 0))
const changeCents = computed(() => givenCents.value - totalCents.value)
const qty = computed(() => props.items.reduce((t, x) => t + x.qty, 0))

// Reset on open
watch(() => props.open, (o) => {
  if (o) {
    stage.value = 'choose'
    givenCents.value = 0
    finished.value = null
    cardError.value = null
    cardWaiting.value = false
  }
})

function setStage(s: Stage) { stage.value = s }

function addDenom(c: number) {
  givenCents.value = Math.min(givenCents.value + c, 99_999_99)
}
function clearGiven() { givenCents.value = 0 }
function backspace() {
  // Treat as "drop one digit" off the decimal representation.
  givenCents.value = Math.floor(givenCents.value / 10)
}
function pressDigit(d: number) {
  const next = givenCents.value * 10 + d
  if (next > 99_999_99) return
  givenCents.value = next
}

const sales = useSalesStore()

async function finishCash() {
  if (givenCents.value < totalCents.value) return
  cardError.value = null
  try {
    const sale = await sales.record({
      method: 'BAR',
      givenCents: givenCents.value,
      items: props.items,
    })
    finished.value = sale
    stage.value = 'done'
    emit('paid', sale)
  } catch (e: any) {
    cardError.value = e?.data?.message ?? 'Buchung fehlgeschlagen.'
  }
}

async function finishCard() {
  cardWaiting.value = true
  cardError.value = null
  try {
    const sale = await sales.record({
      method: 'KARTE',
      givenCents: totalCents.value,
      items: props.items,
    })
    finished.value = sale
    stage.value = 'done'
    emit('paid', sale)
  } catch (e: any) {
    cardError.value = e?.data?.message ?? 'Buchung fehlgeschlagen.'
  } finally {
    cardWaiting.value = false
  }
}

// QR endpoint requires auth — fetch as blob to avoid leaking JWT in the img src URL.
const api = useApi()
const qrUrl = ref<string | null>(null)
let qrAbort: AbortController | null = null

async function loadQr(amount: number) {
  qrAbort?.abort()
  const abort = new AbortController()
  qrAbort = abort
  const prevUrl = qrUrl.value
  qrUrl.value = null
  if (prevUrl) URL.revokeObjectURL(prevUrl)
  try {
    const blob = await api<Blob>('/api/payments/epc-qr.png', {
      query: { amountCents: amount, ref: new Date().toISOString().slice(0, 16) },
      responseType: 'blob',
      signal: abort.signal,
    })
    qrUrl.value = URL.createObjectURL(blob as Blob)
  } catch (e: any) {
    if (e?.name !== 'AbortError') cardError.value = 'QR-Code konnte nicht geladen werden.'
  }
}

watch([() => stage.value, totalCents], ([s, t]) => {
  if (s === 'card' && t > 0) loadQr(t)
}, { immediate: false })

onBeforeUnmount(() => {
  if (qrUrl.value) URL.revokeObjectURL(qrUrl.value)
  qrAbort?.abort()
})

function onBackdropClick(e: MouseEvent) {
  if (e.target === e.currentTarget && stage.value !== 'card') emit('close')
}

const givenDisplay = computed(() => (givenCents.value / 100).toFixed(2).replace('.', ','))
</script>

<template>
  <div v-if="open" class="modal-bg" @mousedown="onBackdropClick">
    <div class="modal" :class="{ wide: stage === 'cash' }">

      <!-- choose stage -->
      <template v-if="stage === 'choose'">
        <div class="modal-h">
          <h3>Bezahlen</h3>
          <p>{{ qty }} Artikel · Bitte Zahlungsmethode wählen</p>
        </div>
        <div class="modal-b">
          <div class="pay-summary">
            <span class="l">Zu zahlen</span>
            <span class="v">{{ formatEUR(totalCents) }}</span>
          </div>
          <div class="pay-row">
            <button class="pay-btn pay-cash" @click="setStage('cash')">
              <span class="ico">💶</span>
              <span>Bar</span>
              <span class="lbl">Bargeld zählen</span>
            </button>
            <button class="pay-btn pay-card" @click="setStage('card')">
              <span class="ico">💳</span>
              <span>Karte</span>
              <span class="lbl">Überweisung per QR</span>
            </button>
          </div>
        </div>
        <div class="modal-f">
          <button class="btn ghost" @click="emit('close')">Abbrechen</button>
        </div>
      </template>

      <!-- cash stage -->
      <template v-else-if="stage === 'cash'">
        <div class="modal-h">
          <h3>Bar bezahlen</h3>
          <p>Auf Geldsymbole tippen oder Betrag eingeben.</p>
        </div>
        <div class="modal-b">
          <div class="pay-summary">
            <span class="l">Zu zahlen</span>
            <span class="v">{{ formatEUR(totalCents) }}</span>
          </div>

          <div class="given-row">
            <div class="given-field">
              <span class="given-l">Gegeben</span>
              <input
                class="given-input"
                inputmode="decimal"
                placeholder="0,00"
                :value="givenDisplay"
                @input="e => {
                  const raw = (e.target as HTMLInputElement).value.replace(/[^\d]/g, '')
                  givenCents = raw === '' ? 0 : Math.min(parseInt(raw, 10), 99_999_99)
                }" />
            </div>
            <button class="btn-clear" @click="clearGiven" title="Zurücksetzen">↻</button>
          </div>

          <div class="money-section">
            <div class="money-label">Scheine</div>
            <div class="money-grid notes-grid">
              <button
                v-for="n in NOTES"
                :key="n.cents"
                :class="['note', `note-${n.cents / 100}`]"
                @click="addDenom(n.cents)">
                <span class="v">{{ n.label }}</span>
              </button>
            </div>
            <div class="money-label">Münzen</div>
            <div class="money-grid coins-grid">
              <button
                v-for="c in COINS"
                :key="c.cents"
                :class="['coin', c.cents >= 100 ? `coin-eu${c.cents / 100}` : (c.cents === 50 ? 'coin-au' : 'coin-cu')]"
                @click="addDenom(c.cents)">
                <span class="v">{{ c.label }}</span>
              </button>
            </div>
          </div>

          <div v-if="givenCents > 0" class="change-line" :class="{ bad: changeCents < 0 }">
            <span class="l">{{ changeCents < 0 ? 'Es fehlen' : 'Rückgeld' }}</span>
            <span class="v">{{ formatEUR(Math.abs(changeCents)) }}</span>
          </div>

          <div v-if="cardError" style="margin-top:10px;color:var(--bad);font-size:13px">{{ cardError }}</div>
        </div>
        <div class="modal-f">
          <button class="btn ghost" @click="setStage('choose')">← Zurück</button>
          <button class="btn ok" :disabled="givenCents < totalCents" @click="finishCash">
            Bezahlung bestätigen
          </button>
        </div>
      </template>

      <!-- card stage -->
      <template v-else-if="stage === 'card'">
        <div class="modal-h">
          <h3>Kartenzahlung · Überweisung per QR</h3>
          <p>Kundinnen-Bankapp öffnen und QR-Code scannen.</p>
        </div>
        <div class="modal-b">
          <div class="card-anim">
            <div class="lab">Betrag</div>
            <div class="v">{{ formatEUR(totalCents) }}</div>
            <div style="margin-top:10px;display:flex;justify-content:center">
              <div style="background:#fff;padding:8px;border-radius:8px;min-width:240px;min-height:240px;display:flex;align-items:center;justify-content:center">
                <img v-if="qrUrl" :src="qrUrl" alt="EPC-QR" width="224" height="224" />
                <span v-else class="status"><span class="pulse"></span>QR wird erzeugt…</span>
              </div>
            </div>
            <div class="status" style="margin-top:10px">
              Mit der Banking-App scannen, um die SEPA-Überweisung anzustoßen.
            </div>
          </div>

          <div v-if="cardError" style="margin-top:10px;color:var(--bad);font-size:13px">{{ cardError }}</div>
        </div>
        <div class="modal-f">
          <button class="btn ghost" @click="setStage('choose')" :disabled="cardWaiting">Abbrechen</button>
          <button class="btn ok" @click="finishCard" :disabled="cardWaiting">
            {{ cardWaiting ? 'Buchen…' : 'Zahlung erhalten' }}
          </button>
        </div>
      </template>

      <!-- done stage -->
      <template v-else-if="stage === 'done' && finished">
        <div class="modal-h">
          <div class="success-ic">✓</div>
          <h3 style="text-align:center">Bezahlt</h3>
          <p style="text-align:center">
            {{ finished.method === 'BAR' ? 'Bar' : 'Karte' }} · {{ formatEUR(finished.totalCents) }} · Vielen Dank!
          </p>
        </div>
        <div class="modal-b">
          <div class="receipt">
            <div class="h">
              <div class="t1">SCHULKASSE · KUCHENVERKAUF</div>
              <div class="t2">{{ new Date(finished.ts).toLocaleString('de-DE') }}</div>
            </div>
            <div v-for="it in finished.items" :key="it.name" class="r">
              <span>{{ it.qty }}× {{ it.name }}</span>
              <span>{{ formatEUR(it.priceCents * it.qty) }}</span>
            </div>
            <div class="sep"></div>
            <div class="r grand"><span>GESAMT</span><span>{{ formatEUR(finished.totalCents) }}</span></div>
            <div class="r"><span>Zahlung</span><span>{{ finished.method === 'BAR' ? 'Bar' : 'Karte' }}</span></div>
            <template v-if="finished.method === 'BAR' && finished.givenCents > 0">
              <div class="r"><span>Gegeben</span><span>{{ formatEUR(finished.givenCents) }}</span></div>
              <div class="r"><span>Rückgeld</span><span>{{ formatEUR(finished.changeCents) }}</span></div>
            </template>
          </div>
        </div>
        <div class="modal-f">
          <button class="btn" @click="emit('close')">Weiter verkaufen →</button>
        </div>
      </template>

    </div>
  </div>
</template>

// design/project/js/PayModal.jsx
// PayModal.jsx — Bezahlflow (Bar + Karte) + Beleg
const { useState, useEffect } = React;

function PayModal({total, items, onClose, onComplete}){
  const [stage, setStage] = useState('choose'); // choose | cash | card | done
  const [given, setGiven] = useState('');
  const [doneInfo, setDoneInfo] = useState(null);
  const givenNum = parseFloat(given.replace(',','.'))||0;
  const change = givenNum - total;

  const kp = (k) => {
    if(k==='⌫'){ setGiven(g=>g.slice(0,-1)); return; }
    if(k===','){ if(!given.includes(',')) setGiven(g=>(g||'0')+','); return; }
    setGiven(g=>{
      const next = g+k;
      if(next.includes(',')){
        const [a,b]=next.split(',');
        if(b && b.length>2) return g;
      }
      return next;
    });
  };

  // Denomination tap-to-add ("ich habe einen 5€-Schein bekommen“)
  const addDenom = (v) => {
    setGiven(g => {
      const cur = parseFloat((g||'0').replace(',','.'))||0;
      const next = +(cur + v).toFixed(2);
      return next.toFixed(2).replace('.',',');
    });
  };
  const clearGiven = () => setGiven('');

  const ceil = n => Math.ceil(n*100)/100;
  const quickRaw = [
    ceil(total),
    Math.ceil(total),
    Math.ceil(total/5)*5,
    Math.ceil(total/10)*10,
  ];
  const uniqQuick = [...new Map(quickRaw.map(v=>[v.toFixed(2), v])).values()].slice(0,4);

  const finishCash = () => {
    if(given==='' || givenNum < total) return;
    const info = {method:'Bar', total, given:givenNum, change};
    setDoneInfo(info);
    onComplete(info);
    setStage('done');
  };

  // Karten-Flow automatisch
  useEffect(()=>{
    if(stage==='card'){
      const t = setTimeout(()=>{
        const info = {method:'Karte', total, given:total, change:0};
        setDoneInfo(info);
        onComplete(info);
        setStage('done');
      }, 1800);
      return ()=>clearTimeout(t);
    }
  },[stage]);

  return (
    <div className="modal-bg" onMouseDown={e=>{if(e.target===e.currentTarget && stage!=='card') onClose()}}>
      <div className={'modal '+((stage==='cash')?'wide':'')}>
        {stage==='choose' && <ChooseStage total={total} items={items}
                                          onCash={()=>setStage('cash')}
                                          onCard={()=>setStage('card')}
                                          onClose={onClose} />}
        {stage==='cash'   && <CashStage total={total} given={given} setGiven={setGiven}
                                        givenNum={givenNum} change={change}
                                        addDenom={addDenom} clearGiven={clearGiven}
                                        kp={kp}
                                        onBack={()=>setStage('choose')}
                                        onConfirm={finishCash} />}
        {stage==='card'   && <CardStage total={total} onCancel={()=>setStage('choose')} />}
        {stage==='done'   && <DoneStage info={doneInfo} items={items} onClose={onClose} />}
      </div>
    </div>
  );
}

function ChooseStage({total, items, onCash, onCard, onClose}){
  const qty = items.reduce((s,x)=>s+x.qty,0);
  return (<>
    <div className="modal-h">
      <h3>Bezahlen</h3>
      <p>{qty} Artikel · Bitte Zahlungsmethode wählen</p>
    </div>
    <div className="modal-b">
      <div className="pay-summary">
        <span className="l">Zu zahlen</span>
        <span className="v">{EUR(total)}</span>
      </div>
      <div className="pay-row">
        <button className="pay-btn pay-cash" onClick={onCash}>
          <span className="ico">💶</span>
          <span>Bar</span>
          <span className="lbl">Bargeld zählen</span>
        </button>
        <button className="pay-btn pay-card" onClick={onCard}>
          <span className="ico">💳</span>
          <span>Karte</span>
          <span className="lbl">Kontaktlos / EC</span>
        </button>
      </div>
    </div>
    <div className="modal-f">
      <button className="btn ghost" onClick={onClose}>Abbrechen</button>
    </div>
  </>);
}

function CashStage({total, given, setGiven, givenNum, change, addDenom, clearGiven, kp, onBack, onConfirm}){
  // Münzen + Scheine: groß = häufige, immer in einer logischen Reihenfolge
  const notes = [
    {v:5,   l:'5\u00a0\u20ac',  cls:'note note-5'},
    {v:10,  l:'10\u00a0\u20ac', cls:'note note-10'},
    {v:20,  l:'20\u00a0\u20ac', cls:'note note-20'},
    {v:50,  l:'50\u00a0\u20ac', cls:'note note-50'},
    {v:100, l:'100\u00a0\u20ac',cls:'note note-100'},
  ];
  const coins = [
    {v:0.05, l:'5\u00a0ct', cls:'coin coin-cu'},
    {v:0.10, l:'10\u00a0ct',cls:'coin coin-cu'},
    {v:0.20, l:'20\u00a0ct',cls:'coin coin-cu'},
    {v:0.50, l:'50\u00a0ct',cls:'coin coin-au'},
    {v:1,    l:'1\u00a0\u20ac', cls:'coin coin-eu1'},
    {v:2,    l:'2\u00a0\u20ac', cls:'coin coin-eu2'},
  ];

  return (<>
    <div className="modal-h">
      <h3>Bar bezahlen</h3>
      <p>Auf Geldsymbole tippen oder Betrag eingeben.</p>
    </div>
    <div className="modal-b">
      <div className="pay-summary">
        <span className="l">Zu zahlen</span>
        <span className="v">{EUR(total)}</span>
      </div>

      {/* Gegeben + Quick clear */}
      <div className="given-row">
        <div className="given-field">
          <span className="given-l">Gegeben</span>
          <input className="given-input" inputMode="decimal" placeholder="0,00"
                 value={given}
                 onChange={e=>setGiven(e.target.value.replace(/[^\d,.]/g,'').replace('.',','))} />
        </div>
        <button className="btn-clear" onClick={clearGiven} title="Zurücksetzen">↻</button>
      </div>

      <div className="money-section">
        <div className="money-label">Scheine</div>
        <div className="money-grid notes-grid">
          {notes.map(n=>(
            <button key={n.v} className={n.cls} onClick={()=>addDenom(n.v)}>
              <span className="v">{n.l}</span>
            </button>
          ))}
        </div>
        <div className="money-label">Münzen</div>
        <div className="money-grid coins-grid">
          {coins.map(c=>(
            <button key={c.v} className={c.cls} onClick={()=>addDenom(c.v)}>
              <span className="v">{c.l}</span>
            </button>
          ))}
        </div>
      </div>

      {(given!=='' && givenNum>0) && (
        <div className={'change-line '+(change<0?'bad':'')}>
          <span className="l">{change<0?'Es fehlen':'Rückgeld'}</span>
          <span className="v">{EUR(Math.abs(change))}</span>
        </div>
      )}
    </div>
    <div className="modal-f">
      <button className="btn ghost" onClick={onBack}>← Zurück</button>
      <button className="btn ok" disabled={given==='' || givenNum<total} onClick={onConfirm}>
        Bezahlung bestätigen
      </button>
    </div>
  </>);
}

function CardStage({total, onCancel}){
  return (<>
    <div className="modal-h">
      <h3>Kartenzahlung</h3>
      <p>Karte an das Lesegerät halten…</p>
    </div>
    <div className="modal-b">
      <div className="card-anim">
        <div className="lab">Betrag</div>
        <div className="v">{EUR(total)}</div>
        <div className="status"><span className="pulse"></span>Verbindung mit Terminal…</div>
      </div>
    </div>
    <div className="modal-f">
      <button className="btn ghost" onClick={onCancel}>Abbrechen</button>
    </div>
  </>);
}

function DoneStage({info, items, onClose}){
  const {total, given, change, method} = info || {};
  return (<>
    <div className="modal-h">
      <div className="success-ic">✓</div>
      <h3 style={{textAlign:'center'}}>Bezahlt</h3>
      <p style={{textAlign:'center'}}>{method} · {EUR(total)} · Vielen Dank!</p>
    </div>
    <div className="modal-b">
      <div className="receipt">
        <div className="h">
          <div className="t1">SCHULKASSE · KUCHENVERKAUF</div>
          <div className="t2">{new Date().toLocaleString('de-DE')}</div>
        </div>
        {items.map(it=>(
          <div className="r" key={it.id}>
            <span>{it.qty}× {it.name}</span>
            <span>{EUR(it.price*it.qty)}</span>
          </div>
        ))}
        <div className="sep"></div>
        <div className="r grand"><span>GESAMT</span><span>{EUR(total)}</span></div>
        <div className="r"><span>Zahlung</span><span>{method}</span></div>
        {method==='Bar' && given>0 && (<>
          <div className="r"><span>Gegeben</span><span>{EUR(given)}</span></div>
          <div className="r"><span>Rückgeld</span><span>{EUR(change)}</span></div>
        </>)}
      </div>
    </div>
    <div className="modal-f">
      <button className="btn" onClick={onClose}>Weiter verkaufen →</button>
    </div>
  </>);
}

window.PayModal = PayModal;
